version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile-app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mongodb://docker.for.mac.localhost:27017/posts

  mongodb:
    build:
      context: .
      dockerfile: dockerfile-db
    ports:
      - "27017:27017"



  #   links:
  #     - mongodb
  #   depends_on:
  #     - mongodb
  #   environment:
  #     DB_HOST: mongodb://docker.for.mac.localhost:27017/posts
  # mongodb:
  #   image: mongo:latest
  #   container_name: "mongodb"
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   volumes:
  #     - ./data/db:/data/db
  #   ports:
  #       - 27017:27017
  #   command: mongod --smallfiles --logpath=/dev/null # --quiet
